/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.okna;

import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author Freeman
 */
public class OProgramieJPanel extends javax.swing.JPanel {
    JFrame parentJFrame;

    /**
     * Creates new form SaveGnuplotDataJPanel
     */
    public OProgramieJPanel(String _title, JFrame parentFrame) {

        
        parentJFrame = parentFrame;
        initComponents();
        //titleLabel.setText(_title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        powrotButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(640, 300));
        setPreferredSize(new java.awt.Dimension(640, 300));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("O programie i autorach");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Program Ekspercki do wyboru programu graficznego.\nPrzygotowany na przedmiot Projekt Zespo³owy,\nprowadzony przez prof. dr. hab. Je¿ego Cytowskiego\nna Wydziale Matematyczno Przyrodniczym\nUniwersystetu Kardyna³a Stefana Wyszyñskiego.\nInformatyka semestr zimowy 2015/2016.\n\nAutorzy:\nWaldemar Sobczak - Pomys³odawca i Kierownik Projektu.\nRafa³ W¹siewicz - G³ówny In¿ynier wykonawczy.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/k14.jpg"))); // NOI18N

        powrotButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        powrotButton.setText("Powrót");
        powrotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powrotButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(powrotButton, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(powrotButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void powrotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powrotButtonActionPerformed
        //parentJFrame.setVisible(false);
        parentJFrame.dispatchEvent(new WindowEvent(parentJFrame, WindowEvent.WINDOW_CLOSING));
        ((OProgramieJFrame)parentJFrame).getParentJFrame().setVisible(true);
    }//GEN-LAST:event_powrotButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton powrotButton;
    // End of variables declaration//GEN-END:variables

//private XYSeriesCollection privGetDatColl(PopulationData _popDat, int _chartNumber){
//    DataExtractor traktor = new DataExtractor();
//    XYSeriesCollection datCol;
//    
//    if(_chartNumber == 3){
//        String nazwyPopulation[] = new String[4];
//        nazwyPopulation[0] = "Best lifes LT";
//        nazwyPopulation[1] = "Best first death LT";
//        nazwyPopulation[2] = "Best global LT";
//        nazwyPopulation[3] = "Average Life Time";
//        
//        
//        return   traktor.TEST_extractDataPopulationPlot(popDat,
//                                                        plotService.getSelectedGenerationNumber(),
//                                                        nazwyPopulation,
//                                                        filter);
//    }
//    if(_chartNumber == 2){
//        String nazwyGeneration[] = new String[4];
//        nazwyGeneration[0] = "LT with lifes";
//        nazwyGeneration[1] = "LT first death";
//        nazwyGeneration[2] = "LT global";
//        nazwyGeneration[3] = "Average Life Time";
//        
//        return   traktor.TEST_extractDataGenerationPlot(popDat.get(plotService.getSelectedGenerationNumber()),
//                                                        plotService.getSelectedIndividualNumber(),
//                                                        nazwyGeneration,
//                                                        filter);
//    }
//    if(_chartNumber == 1){
//        String nazwyIndividual[] = new String[3];
//        nazwyIndividual[0]="Coverange";
//        nazwyIndividual[1]="Percent of dead sensors";
//        nazwyIndividual[2]="Desired Coverange";
//        
//        return   traktor.TEST_extractDataIndividualPlot(popDat.get( plotService.getSelectedGenerationNumber()).get(plotService.getSelectedIndividualNumber()),    
//                                                        plotService.getDesireCoverage(),
//                                                        plotService.getShowDeadSensors(),
//                                                        plotService.getSelectedTimeslapNumber(),
//                                                        nazwyIndividual);
//    
//    }
////    if(_chartNumber == 0){
////        datCol = traktor.extractDataForScatterPlot( popDat.get( plotService.getSelectedGenerationNumber()).get(plotService.getSelectedIndividualNumber()).get(plotService.getSelectedTimeslapNumber()),    
////                                                    null);
////    }
//    else return null;
//
//}


}



